#!/bin/bash
if [[ "$1" =~ ^2[0-9]{3}$ ]]; then
    year=$1
elif [[ "$1" =~ ^[0-9]{2}$ ]]; then
    year=20$1
fi
if [[ "$2" =~ ^[0-3][0-9]$ ]]; then
    day=$2
elif [[ "$2" =~ ^[1-9]$ ]]; then
    day=0$2
fi

if [[ $# -ne 2 || -z "$year" || -z "$day" ]]; then
    echo "Syntax: `basename "$0"` <yyyy> <dd>"
    exit 0
fi

AOC_DIR=~/advent-of-code

if [ ! -d $AOC_DIR/$year ]; then
    echo Directory $year does not exist
    exit 1
fi

if [ -d $AOC_DIR/$year/day$day ]; then
    echo Directory $year/day$day already exists
    exit 1
fi

mkdir $AOC_DIR/$year/day$day

cat << EOF > $AOC_DIR/$year/day$day/day$day.py
#!/usr/bin/env python

import fileinput

def function1(d): 
    return int(d)

def function2(d): 
    return int(d)

if __name__ == '__main__':
    for n, line in enumerate(fileinput.input()):
        print 'Executing function1 on line', (n + 1), 'returned', function1(line)
        print 'Executing function2 on line', (n + 1), 'returned', function2(line)
EOF

cat << EOF >> $AOC_DIR/$year/day$day/tests.py
#!/usr/bin/env python

import unittest

from day$day import function1, function2

class TestDay$day(unittest.TestCase):
    def test_part_one(self):
        self.assertEqual(function1('0'), 0)

    def test_part_two(self):
        self.assertEqual(function2('0'), 0)

if __name__ == '__main__':
    unittest.main()
EOF

chmod +x $year/day$day/day$day.py
chmod +x $year/day$day/tests.py
